import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });
import Header from '@/app/components/navbar.js'
import Footer from '@/app/components/footer.js'


export const metadata: Metadata = {
  title: "QuizCrafters",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
